/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LotsIndexRouteImport } from './routes/lots/index'
import { Route as LotsLotIdRouteImport } from './routes/lots/$lotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsIndexRoute = LotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsLotIdRoute = LotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiry': typeof InquiryRoute
  '/location': typeof LocationRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/lots/': typeof LotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiry': typeof InquiryRoute
  '/location': typeof LocationRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/lots': typeof LotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquiry': typeof InquiryRoute
  '/location': typeof LocationRoute
  '/lots/$lotId': typeof LotsLotIdRoute
  '/lots/': typeof LotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inquiry' | '/location' | '/lots/$lotId' | '/lots/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inquiry' | '/location' | '/lots/$lotId' | '/lots'
  id: '__root__' | '/' | '/inquiry' | '/location' | '/lots/$lotId' | '/lots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquiryRoute: typeof InquiryRoute
  LocationRoute: typeof LocationRoute
  LotsLotIdRoute: typeof LotsLotIdRoute
  LotsIndexRoute: typeof LotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/': {
      id: '/lots/'
      path: '/lots'
      fullPath: '/lots/'
      preLoaderRoute: typeof LotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$lotId': {
      id: '/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/lots/$lotId'
      preLoaderRoute: typeof LotsLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquiryRoute: InquiryRoute,
  LocationRoute: LocationRoute,
  LotsLotIdRoute: LotsLotIdRoute,
  LotsIndexRoute: LotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
